<?php

Class Userpanel_model extends CI_Model {


   function addComplaint($data){
    $this->db->insert('complaint', $data);
    $lastid=$this->db->insert_id();
    $history=array(
      'complaintId' => $lastid,
      'compstatus' =>'Complaint Registered in portal',
      'statusupdate'=>time(),
    );
    $this->db->insert('complainthistory', $history);
    return $lastid;
   }

   function updatePayment($registrationData,$insertid){
    $this->db->where('complaint_id',$insertid)->update('complaint',$registrationData);
    $history=array(
      'complaintId' => $insertid,
      'compstatus' =>'Amount Paid successfully',
      'statusupdate'=>time(),
    );
    $this->db->insert('complainthistory', $history);
   }

   function updateExtraPayment($registrationData,$insertid){
      $this->db->where('extrapaymentid',$insertid)->update('extrapayment',$registrationData);
      $check=$this->db->select('complaintid')->from('extrapayment')->where('extrapaymentid',$insertid)->get()->row_array();

      $history=array(
         'complaintId' => $check['complaintid'],
         'compstatus' =>'Extra Amount Paid successfully',
         'statusupdate'=>time(),
       );
       $this->db->insert('complainthistory', $history);
   }

   function getComplaintList($userid,$status=null,$limit=null){
      $this->db->select('complaint.*,complaintstatus.status as compstatus,complaint_type.*,IFNULL(staff.name,"Not Assigned") as staffname');
      $this->db->from('complaint');
      $this->db->join('complaintstatus','complaintstatus.statusId =complaint.complaintStatus');
      $this->db->join('complaint_type','complaint_type.typeid =complaint.complaint_type');
      $this->db->join('staff','staff.staff_id = complaint.assignedTo','left');
      $this->db->where('complaint.registeredBy',$userid);
      $this->db->order_by('complaint.complaint_id','desc');
      if($status!=null){
         $this->db->where('complaint.complaintStatus',$status);
      }
      if ($limit !=null) {
         $this->db->limit($limit);
      } 
      $query = $this->db->get();
      return $query->result_array();

   }

   function getSingleComplaintList($compid,$userid){
      //fetching single complaint details from database
      $this->db->select('complaint.complaintStatus,complaintstatus.status,complaint.subject,complaint.stars as stars, complaint.feedback as feedback,complaint.assignedTo,
      IFNULL(staff.name,"Not Assigned") as staffname,complaint.registeredBy,complaint.complaint_type,complaint.description,users.name,users.building,
      users.roomno,complaint_type.typename,complaint.complaintDate,complaint.lastupdate');
      $this->db->from('complaint');
      $this->db->join('staff','staff.staff_id = complaint.assignedTo','left');
      $this->db->join('users','users.userid= complaint.registeredBy');
      $this->db->join('complaint_type','complaint_type.typeid=complaint.complaint_type');
      $this->db->join('building','building.buildingid=users.building');
      $this->db->join('complaintstatus','complaintstatus.statusId=complaint.complaintStatus');
      $this->db->where('complaint.complaint_id',$compid);
      $this->db->where('complaint.registeredBy',$userid);
 
      $query=$this->db->get();
      //echo $this->db->last_query();   //this line of code is used to print the sql statement generated by above function
      return $query->row_array();
      
   }

   function getComplaintHistory($id,$user){
   //this function used to fetch complaint history for a particular complaint and user
   //we take complaint id and user id of logged in user and return result as array
   $this->db->select('complainthistory.*,complaint.complaint_id,complaint.assignedTo');
   $this->db->from('complainthistory');
   $this->db->join('complaint','complaint.complaint_id=complainthistory.complaintId');
   $this->db->where('complaint.registeredBy',$user);
   $this->db->where('complainthistory.complaintId',$id);
   $this->db->order_by('complainthistory.comphistid','asc');
   $query = $this->db->get();
   //echo $this->db->last_query();
   return $query->result_array();

   }

   function getextraPayment($id,$user){
    //this function used to fetch extra payment requirement details for a particular complaint and user
   //we take complaint id and user id of logged in user and return result as array
      $this->db->select('extrapayment.*,complaint.complaint_id,staff.name as raiseby,staff.staff_id');
      $this->db->from('extrapayment');
      $this->db->join('complaint','complaint.complaint_id=extrapayment.complaintid');
      $this->db->join('staff','staff.staff_id=extrapayment.raisedby','left');
      $this->db->where('complaint.registeredBy',$user);
      $this->db->where('extrapayment.complaintid',$id);
      $this->db->order_by('extrapayment.extrapaymentid','asc');
      $query = $this->db->get();
      //echo $this->db->last_query();
      return $query->result_array();
   }


   function getChatMessage($chatroomid,$startid=null){
      //get chat message
      $this->db->select('*');
      $this->db->from('chatmessage');
      $this->db->where('chatroomid',$chatroomid);
      if($startid!=null){
      $this->db->where('messageid >',$startid);
      }
      $this->db->order_by('timestamp','asc');
      $query = $this->db->get();
      return $query->result_array();

   }

   function fetchRatings($staffid,$type=null){
      //fetch ratings from complaint table using staff if filter
      $this->db->select('complaint.complaint_id,complaint.stars,complaint.feedback,complaint.lastupdate,users.name as uname');
      $this->db->from('complaint');
      $this->db->join('users', 'users.userid = complaint.registeredBy','left');
      $this->db->where('assignedTo',$staffid);
      $this->db->where('assignedTo !=',0);
      if($type!=null){
      $this->db->where('stars',$type);
      }
      $this->db->where('complaint.stars !=',null);
      $query = $this->db->get();
      //echo $this->db->last_query();
      return $query->result_array();
   }

   function getUserDetails($userid){
      //getting user details from datbase using session data
      $this->db->select('users.*,buildingname');
      $this->db->from('users');
      $this->db->join('building','building.buildingid = users.building');
      $this->db->where('users.userid',$userid);
      $query=$this->db->get();
      return $query->row_array();
   }

   function getComplaintType(){
      //complaint type list as array
      $this->db->select('complaint_type.*');
      $this->db->from('complaint_type');
      $query=$this->db->get();
      return $query->result_array();

   }

   function getcomplaintNo($orderid){
      //getting complaint no from database using paymentTransactionId
      $this->db->select('complaint.complaintNo');
      $this->db->from('complaint');
      $this->db->where('complaint.paymentTransactionId',$orderid);
      $query=$this->db->get();
      $result=$query->row_array();
      return $result['complaintNo'];
   }





}

?>